import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {onRequest} from '../functions/api/visits.js';
const db=new DatabaseSync(':memory:');
db.exec(readFileSync(new URL('../migrations/0001_visit_counter.sql',import.meta.url),'utf8'));
const wrap=(sql,args=[])=>({sql,args,bind(...values){return wrap(sql,values);},async first(){return db.prepare(sql).get(...args);}});
const env={VISITS_DB:{prepare:wrap,async batch(statements){db.exec('BEGIN');try{const results=statements.map(({sql,args})=>sql.startsWith('SELECT')?{results:db.prepare(sql).all(...args)}:{results:[],meta:db.prepare(sql).run(...args)});db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const url='https://techatlas-aoh.pages.dev/api/visits';
const token='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const call=(method='GET',body,origin='https://techatlas-aoh.pages.dev')=>onRequest({env,request:new Request(url,{method,headers:{Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)})});
assert.equal((await (await call()).json()).total,0);
assert.equal((await (await call('POST',{token})).json()).total,1);
assert.equal((await (await call('POST',{token})).json()).total,1);
assert.equal((await (await call('POST',{token:other})).json()).total,2);
assert.equal((await call('POST',{token:'bad'})).status,400);
assert.equal((await call('POST',{token},'https://untrusted.test')).status,403);
assert.equal((await call('PUT',{token})).status,405);
assert.equal((await call('POST',{token:'x'.repeat(1000)})).status,413);
db.exec("UPDATE visit_sessions SET created_at = datetime('now','-31 days')");
assert.equal((await (await call('POST',{token})).json()).total,3);
assert.equal(db.prepare('SELECT count(*) AS n FROM visit_sessions').get().n,1);
assert.equal((await onRequest({request:new Request(url),env:{}})).status,503);
db.close();console.log('PASS: real SQLite counter, deduplication, retention, origin/method/token/size checks, missing binding');
