import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {onRequest} from '../functions/api/visits.js';
const db=new DatabaseSync(':memory:');
db.exec(readFileSync(new URL('../migrations/0001_visit_counter.sql',import.meta.url),'utf8'));
db.exec(readFileSync(new URL('../migrations/0002_counter_maintenance.sql',import.meta.url),'utf8'));
const wrap=(sql,args=[])=>({sql,args,bind(...values){return wrap(sql,values);},async first(){return db.prepare(sql).get(...args);}});
const env={VISITS_DB:{prepare:wrap,async batch(statements){db.exec('BEGIN');try{const results=statements.map(({sql,args})=>sql.startsWith('SELECT')?{results:db.prepare(sql).all(...args)}:{results:[],meta:db.prepare(sql).run(...args)});db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const url='https://techatlas-aoh.pages.dev/api/visits';
const token='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const call=(method='GET',body,origin='https://techatlas-aoh.pages.dev')=>onRequest({env,request:new Request(url,{method,headers:{Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)})});
assert.equal((await (await call()).json()).total,0);
assert.equal((await (await call('POST',{token})).json()).total,1);
assert.equal((await (await call('POST',{token})).json()).total,1);
assert.equal((await (await call('POST',{token:other})).json()).total,2);
assert.equal((await call('POST',{token:'bad'})).status,400);
assert.equal((await call('POST',{token},'https://untrusted.test')).status,403);
assert.equal((await call('PUT',{token})).status,405);
assert.equal((await call('POST',{token:'x'.repeat(1000)})).status,413);
db.exec("UPDATE visit_sessions SET created_at = datetime('now','-31 days')");
db.exec("UPDATE visit_maintenance SET cleaned_at = datetime('now','-2 days')");
assert.equal((await (await call('POST',{token})).json()).total,3);
assert.equal(db.prepare('SELECT count(*) AS n FROM visit_sessions').get().n,1);
const writesBefore=db.prepare('SELECT total_changes() AS n').get().n;
await call('POST',{token});
assert.equal(db.prepare('SELECT total_changes() AS n').get().n,writesBefore,'duplicate token makes no writes');
for(let i=0;i<59;i++){
 const token=`${(i+10).toString(16).padStart(8,'0')}-3333-4333-8333-333333333333`;
 assert.equal((await call('POST',{token})).status,200);
}
const denied=await call('POST',{token:'ffffffff-ffff-4fff-8fff-ffffffffffff'});
assert.equal(denied.status,429);assert.equal(denied.headers.get('Retry-After'),'60');
assert.equal((await call('POST',{token})).status,200,'existing sessions can read even when admission is full');
assert.equal(db.prepare('SELECT count(*) AS n FROM visit_sessions').get().n,60);
assert.equal((await call()).headers.get('Cache-Control'),'public, max-age=30');
db.exec("UPDATE visit_sessions SET created_at = datetime('now','-2 minutes'); UPDATE visit_maintenance SET admission_day = date('now'), admitted_today = 2000");
assert.equal((await call('POST',{token:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'})).status,429,'daily admission budget');
db.exec("UPDATE visit_maintenance SET admission_day = date('now','-1 day')");
assert.equal((await call('POST',{token:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'})).status,200,'budget resets by UTC date');
assert.equal(db.prepare('SELECT admitted_today FROM visit_maintenance').get().admitted_today,1);
const cachedResponses=new Map(),pending=[];
globalThis.caches={default:{async match(key){return cachedResponses.get(key.url)?.clone();},async put(key,response){cachedResponses.set(key.url,response);}}};
const cacheCall=()=>onRequest({env,request:new Request(url),waitUntil:p=>pending.push(p)});
await cacheCall();await Promise.all(pending);
const savedPrepare=env.VISITS_DB.prepare;env.VISITS_DB.prepare=()=>{throw Error('cache should avoid DB read')};
assert.equal((await cacheCall()).status,200);env.VISITS_DB.prepare=savedPrepare;delete globalThis.caches;
assert.equal((await onRequest({request:new Request(url),env:{}})).status,503);
db.close();
const existing=new DatabaseSync(':memory:');existing.exec(readFileSync(new URL('../migrations/0001_visit_counter.sql',import.meta.url),'utf8'));existing.exec("INSERT INTO visit_sessions(token) VALUES ('existing-session')");
existing.exec(readFileSync(new URL('../migrations/0002_counter_maintenance.sql',import.meta.url),'utf8'));
assert.equal(existing.prepare('SELECT total FROM visit_totals').get().total,1,'migration preserves aggregate');assert.equal(existing.prepare('SELECT count(*) AS n FROM visit_sessions').get().n,1,'migration preserves sessions');existing.close();
console.log('PASS: SQLite migration preservation, dedup zero-write, retention, validation, minute/daily admission and UTC reset');
